# Generated by Django 3.1 on 2020-12-03 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('misc', 'misc'), ('computers', 'computers'), ('toys', 'toys'), ('pets', 'pets'), ('beauty', 'beauty'), ('video games', 'video games'), ('food', 'food'), ('clothing', 'clothing')], default='misc', max_length=30)),
                ('listing_title', models.CharField(max_length=100)),
                ('listing_description', models.TextField(max_length=1200)),
                ('listing_img', models.URLField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('active_flag', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='active listing')),
                ('listing_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('listing_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
