# Generated by Django 3.1 on 2020-12-05 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_ending_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ending_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='final_price'),
        ),
    ]
