# Generated by Django 3.1 on 2020-12-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201205_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ending_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_winner',
        ),
    ]
