# Generated by Django 3.1 on 2020-12-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201207_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='item',
        ),
    ]
