# Generated by Django 3.1 on 2020-12-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20201210_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='listing',
        ),
    ]
