# Generated by Django 3.1 on 2020-12-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20201210_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='item',
        ),
    ]
