# Generated by Django 3.1 on 2020-12-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20201211_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='listing',
        ),
    ]
