# Generated by Django 3.1 on 2020-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20201213_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
