# Generated by Django 3.1 on 2020-12-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20201215_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active_flag',
        ),
        migrations.AddField(
            model_name='listing',
            name='closed_auction',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
